/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c2b659be-c327-4273-ac3b-dc6b459a8977",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_oD1UYlwzL",
    "aws_user_pools_web_client_id": "42m5v7ho89e5i09j34pheg5h54",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://tqr2pbtw55h7paqiqohqu6jreu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vitmm3uixvakfp6o4uostma2y4"
};


export default awsmobile;
